### ISSUE TITLE
Does it only shows the buttons?

### ISSUE THREAD

**Issue by luizptm** [tiagoporto/accessibility-buttons#15]
For me, the buttons don't do anything.

**Comment by tiagoporto** [comment]
Hi @luizptm, could you describe the bug? There are some messages in console or could you share a repository with your implementation?

**Comment by tiagoporto** [comment]
Check the [demo page](http://tiagoporto.github.io/accessibility-buttons/)

**Comment by luizptm** [comment]
Thanks.
