### ISSUE TITLE
Validation for subject and message field is not working

### ISSUE THREAD

**Issue by aparna-github157** [tiagoporto/accessibility-buttons#23]
I am creating an email app. First fill the from and to fields and then when click send that links via Ajax to a php script which then sends the e-mail and returns true and the app interprets this as a successful send. It will also validate the form before sending and the recipient email addresses which are used automatically appear in the email address list.

Everything is working except the subject and message. The validation for a subject and message is not working, even it's sending the mail without subject and message.

I have attached two files. Please go through the code.

[indexxPage.txt](https://github.com/tiagoporto/accessibility-buttons/files/4842914/indexxPage.txt)
![sendEmail](https://user-images.githubusercontent.com/64718125/85956890-84af1d80-b9a6-11ea-8f77-d1596f5bac4a.png)

Any help would be appreciated.

Thanks

**Comment by tiagoporto** [comment]
The validation isn't a php issue, you need prevent form submission before post.

Check this tread, about `event.preventDefault()`

https://www.sitepoint.com/community/t/how-to-set-up-preventdefault-on-form-submit/245580/2

**Comment by aparna-github157** [comment]
Thanks for the reply.

I have already used preventDefault in the beginning:

 $(page).find('#send')
	     .clickable()
	     .on('click', function (e) {
			
		e.preventDefault();
}

But it's working only for from and to emails, but not for subject and message. Even if the subject and message fields are not filled, it's sending the mail.
