### ISSUE TITLE
Extend use with data attribute or class

### ISSUE THREAD

**Issue by lowpez** [tiagoporto/accessibility-buttons#24]
Hi Tiago!
I hope you are super well,
First of all! Thank you. I'm using your script accessibility buttons, which is excellent.
I would like to know if you could help me with something:
I'm trying to extend the functionality to other elements like data-* or class.
Why? Simple what if i need to put a button in a header and footer or some dummy esthetic thing :P ?
Use the same ID atrib, is like all know, invalid. Both, for the W3c and for all screen readers.
That's why i'm trying to replace the use of the ID by a data-id or class,

I made some adjustments but with no luck. I leave you the [Pastebin](https://pastebin.com/MuvN96xi)

Another cool stuff would be use a valid role="switch".

Thank you very much!

**Comment by tiagoporto** [comment]
Fixed on [v4.0.0](https://github.com/tiagoporto/accessibility-buttons/releases/tag/v4.0.0)

**Comment by lowpez** [comment]
Gracias @tiagoporto !
U rock!

**Comment by tiagoporto** [comment]
Thank you :metal:
