### ISSUE TITLE
README.pt_br.md - 404 - page not found

### ISSUE THREAD

**Issue by wfrsilva** [tiagoporto/accessibility-buttons#28]
Ao abrir o "Veja como Contribuir" acusa erro 404.
![image](https://github.com/tiagoporto/accessibility-buttons/assets/8933834/b9d651fe-e124-40aa-a91d-3a52e94c9c8d)

Onde encontra o link:
https://github.com/tiagoporto/accessibility-buttons/blob/master/translations/README.pt_br.md

 
 

![image](https://github.com/tiagoporto/accessibility-buttons/assets/8933834/bef84e3d-e9e7-4bb3-9528-40b50bd3a853)

Para onde ele aponta:
https://github.com/tiagoporto/accessibility-buttons/blob/master/translations/CONTRIBUTING.md

[accessibility-buttons](https://github.com/tiagoporto/accessibility-buttons/tree/master)/[translations](https://github.com/tiagoporto/accessibility-buttons/tree/master/translations)/CONTRIBUTING.md/

404 - page not found 
The master
 branch of accessibility-buttons does not contain the path translations/CONTRIBUTING.md.

**Comment by tiagoporto** [comment]
Fixed on #29
