### ISSUE TITLE
Check spelling errors

### ISSUE THREAD

**Issue by tiagoporto** [tiagoporto/accessibility-buttons#6]

**Comment by JoyceZhu** [comment]
I could take a look at this. Are there any specific files you're looking to target for finding spelling errors?

**Comment by tiagoporto** [comment]
Hi @JoyceZhu, cool!

Please, take a look in `README.md` and `dist/index.html`.

This is [index.hmtl](http://tiagoporto.github.io/accessibility-buttons/)
